import type {Metadata} from 'next'
import {Inter as FontSans, Montserrat} from "next/font/google"
import './globals.css'
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import {CookiesProvider} from "next-client-cookies/server";
import Providers from "@/app/providers";
import ConditionalLayout from "@/components/ConditionalLayout";
import {cn} from "@/utils/twMerge";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-mont",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <CookiesProvider>
          <html lang="en">
          <body className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable, montserrat.variable
          )}>
          <Providers>
              <ConditionalLayout>
                  <Header/>
                  <Sidebar/>
              </ConditionalLayout>
              <div className="w-[calc(100% - 5rem)] h-[calc(100vh-60px)] ml-20">
                  {children}
              </div>
          </Providers>
          </body>
          </html>
      </CookiesProvider>
  )
}
