import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import {CookiesProvider} from "next-client-cookies/server";
import Providers from "@/app/providers";
import ConditionalLayout from "@/components/ConditionalLayout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <CookiesProvider>
          <html lang="en">
          <body className={inter.className}>
          <Providers>
              <ConditionalLayout>
                  <Header/>
                  <Sidebar/>
              </ConditionalLayout>
              {children}
          </Providers>
          </body>
          </html>
      </CookiesProvider>
  )
}
